# Generated by Django 5.2.7 on 2025-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommend', '0002_alter_myuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='MovieRecommend.genre'),
        ),
    ]
