# Generated by Django 5.2.7 on 2025-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommend', '0003_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
