# Generated by Django 5.2.7 on 2025-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommend', '0005_alter_movie_rating_listtowatch_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='MovieRecommend.genre'),
        ),
    ]
