# Generated by Django 5.2.7 on 2025-10-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommend', '0006_alter_movie_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listToWatch',
            new_name='WatchedMovies',
        ),
    ]
