# Generated by Django 5.2.7 on 2025-10-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommend', '0007_rename_listtowatch_watchedmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedmovies',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='watchedmovies',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchedmovies',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='MovieRecommend.movie'),
        ),
        migrations.AlterField(
            model_name='watchedmovies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
